### ISSUE TITLE
请问有基于vue-cli3的版本吗

### ISSUE THREAD

**Issue by Liubasara** [DendiSe7enGitHub/Align#1]
非常不错的blog生成框架！请问作者有将项目升级移植至vue-cli3的想法吗？

**Comment by DendiSe7enGitHub** [comment]
hi~

暂时还没有呢，但是，cli3的具体优势是什么呀？

**Comment by DendiSe7enGitHub** [comment]
> 非常不错的blog生成框架！请问作者有将项目升级移植至vue-cli3的想法吗？

有更多的建议可以新开issues哦
