### ISSUE TITLE
发不出请求？

### ISSUE THREAD

**Issue by smalltimoo** [DendiSe7enGitHub/Align#2]
我在你这个代码的基础上用的你的axios@0.16.2 发现发不出请求

![1](https://user-images.githubusercontent.com/19339167/51234059-a11feb80-19a6-11e9-9689-ac5af01373a1.png)
![2](https://user-images.githubusercontent.com/19339167/51234079-abda8080-19a6-11e9-92b5-9201f53a713d.png)
然而这个api在liu浏览器中是可以正常访问的，我该怎么做呢

**Comment by DendiSe7enGitHub** [comment]
> 我在你这个代码的基础上用的你的axios@0.16.2 发现发不出请求
> 
> ![1](https://user-images.githubusercontent.com/19339167/51234059-a11feb80-19a6-11e9-9689-ac5af01373a1.png)
> ![2](https://user-images.githubusercontent.com/19339167/51234079-abda8080-19a6-11e9-92b5-9201f53a713d.png)
> 然而这个api在liu浏览器中是可以正常访问的，我该怎么做呢

axios的请求我是没有进行封装和使用的，package.json 中也没有引入这个包，如果说你想使用的话，就参考 axios的官方文档吧~ 或者你可以提供给我一个完整的 `.vue` 文件 可以给你一些参考意见。
